version: "3.9"

services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                VERSION: "${VERSION}"
        image: ${IMAGE_NAME}:${VERSION}
        container_name: ${IMAGE_NAME}
        ports:
            - "${PORT}:${PORT}"
        tty: true        